### ISSUE TITLE
Filter vs Export versie 4.1

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#1]
@luukverhoeven Ik loop nu tegen een probleem aan in de 4.1 versie van het blok COonfigurable report. 
Bijgaand heb je een database query met diverse filters. 

Wanneer we de filter gebruiken wordt dit goed getoond op de pagina zelf. Maar bij de export worden ALLE records meegenomen. 
![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/817ccbb3-14ba-4bdb-9e46-2d6019d89a50)

**Comment by luukverhoeven** [comment]
@gemguardian Bij de oude versie van de plug-in kwam alleen de geselecteerde data terug die binnen de filters aanwezig was?

**Comment by gemguardian** [comment]
@luukverhoeven  ik denk dat we elkaar goed begrijpen en het antwoord ja is. 

In de oude versie van de Plugin maakte ik een filtering, dit werd dan op het scherm getoond zoals in de screenshot. En dan zou ik bij de Excel/CSV import alleen deze regel terug zien en niet alle regels uit de database query.

**Comment by luukverhoeven** [comment]
Zie nu ook je mail, daarin staat het ook dat het eerder correct werkt. Ik ga het onderzoeken, staat op de lijst.

**Comment by gemguardian** [comment]
@luukverhoeven kun jij aangeven wanneer je hier mee aan de slag gaat? 

@servicedeskltnc

**Comment by luukverhoeven** [comment]
@gemguardian Deze stond op de todo, maar had geen duedata :( 

Het issue heb ik gevonden, kun je testen of naar wens werkt?

**Comment by gemguardian** [comment]
@luukverhoeven dit werkt - net nu hij doorgezet heeft naar 4.1 :) Kun je deze fix pushen naar de orginele en meldde wat het issue was?

**Comment by luukverhoeven** [comment]
@gemguardian Pull request aangemaakt, https://github.com/jleyva/moodle-block_configurablereports/pull/248
