### ISSUE TITLE
M4.1 - PHP 8.1 | Bar and Line graph image don't work 

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#2]
@luukverhoeven could you please check if this is something that is caused by our changes or already was broken ? 

If so - and it is not part of the bug support anymore - could you please let me know what the time is to fix this? 

You can download the XML file from: https://www.ltncbestanden.nl/s/kPG6E05jTvebTv1f since Github refuses the upload. 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/c31c14f5-3512-45f1-acfe-6c1f686e1d62)

When I select the urls from the inspect tool I get the following errors
![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/73e018b7-d2c1-46a5-a288-bb8ea1c5cc69)

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/8c23b30c-1108-40dd-a78c-bf328846c643)

**Comment by luukverhoeven** [comment]
@gemguardian Kun je de link naar de afbeelding delen? Ik krijg geen foutmelding met jouw voorbeeld, mogelijk omdat er niet voldoende data in mijn omgeving aanwezig is.

**Comment by gemguardian** [comment]
AFbeelding 1: https://test.edubus.moodle.tvo.rimotecloud.com/blocks/configurable_reports/components/plot/bar/graph.php?reportid=9&amp;id=Bzn23onDehVaDIW&amp;graphdata=%7B%22month%22%3A%5B%22May+2023%22%2C%22June+2023%22%2C%22July+2023%22%2C%22August+2023%22%2C%22September+2023%22%2C%22November+2023%22%2C%22March+2024%22%5D%2C%22users%22%3A%5B%22817%22%2C%22790%22%2C%22665%22%2C%22251%22%2C%221%22%2C%222%22%2C%222%22%5D%7D

Afbeelding 2: https://test.edubus.moodle.tvo.rimotecloud.com/blocks/configurable_reports/components/plot/line/graph.php?reportid=9&amp;id=q6IyOKXEjKcCcey&amp;serie0=ODE3fHww&amp;serie1=NzkwfHww&amp;serie2=NjY1fHww&amp;serie3=MjUxfHww&amp;serie4=MXx8MA==&amp;serie5=Mnx8MCww&amp;min=0&amp;max=0

Afbeelding 3 (die wel toont) https://test.edubus.moodle.tvo.rimotecloud.com/blocks/configurable_reports/components/plot/pie/graph.php?reportid=9&amp;id=vaNshIi3nDedfDi&amp;serie0=TWF5IDIwMjMsSnVuZSAyMDIzLEp1bHkgMjAyMyxBdWd1c3QgMjAyMyxTZXB0ZW1iZXIgMjAyMyxOb3ZlbWJlciAyMDIzLE1hcmNoIDIwMjQ=&amp;serie1=MSwxLDEsMSwxLDEsMQ==&amp;colorpalette=LCwsLCws

**Comment by luukverhoeven** [comment]
@gemguardian Ik kon daar meerdere issues in vinden. Ik weet niet of het eerder goed heeft gewerkt. Kun je testen of de laatste aanpassing in `MOODLE41` branch correct werkt? 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/995760/35abad3a-4fda-4298-acc8-bcac1b1e27d8)

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/995760/2b07fda3-a2c9-4b36-8652-faa17dd2eacb)

**Comment by gemguardian** [comment]
@luukverhoeven 1 van de 'balken' werkt er nu, maar de 2de nog niet 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/78433306-e241-43f7-a472-844451048600)

URL: https://test.edubus.moodle.tvo.rimotecloud.com/blocks/configurable_reports/components/plot/line/graph.php?reportid=9&amp;id=q6IyOKXEjKcCcey&amp;serie0=ODE3fHww&amp;serie1=NzkwfHww&amp;serie2=NjY1fHww&amp;serie3=MjUxfHww&amp;serie4=MXx8MA==&amp;serie5=Mnx8MCww&amp;min=0&amp;max=0

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/16559999/40e5a9f2-00b2-4936-a8e9-208af7cdefd9)

**Comment by luukverhoeven** [comment]
@gemguardian Kun je de laatste versie testen? Ik vond een mogelijke fout, maar ik kan dit niet goed lokaal testen vanwege te weinig data. Misschien is het ook goed om de instellingen van de plot in deze rapportage te controleren.

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/995760/44b8c12f-5827-437a-ab41-639d4339b343)

**Comment by gemguardian** [comment]
@luukverhoeven ik heb geprobeerd met aangepaste instellingen maar ik krijg het niet zichtbaar. Ik ga het doorzetten naar de melder, wellicht dat het hem lukt om data te tonen want mij lukt het niet. Maar ik werk dus ook nooit mee om te weten wat ik dan fout doe.

**Comment by gemguardian** [comment]
@luukverhoeven ik heb contact gehad met de melder van het issue. Deze is momenteel met vakantie en zal gaan testen als hij terug is. Dit zal dus de komende 2-3 weken in ieder geval nog stil liggen.

**Comment by gemguardian** [comment]
@luukverhoeven I have not received any response from Darrel who pointed it out. As far as I can see this is fixed. I belive you have it in the 4.1 branche. If so we close this comment.

**Comment by Jay-lab-1** [comment]
@gemguardian:

Hi,

I have tested version 4.1.0 of the block_configurable_reports plugin in Moodle 4.3 with PHP8.0.30 and PHP8.1.28 and found that none of the three selectable charts (Bar, Line, Pie) now generate images (05.06.24).

I get the following error messages in the web console
![Screenshot from 2024-06-05 15-10-00](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/assets/174424658/11387f0e-9f9f-4753-b259-684f0bc3e37c)

Since I haven't seen an update in the branch, I wanted to ask if this bug has been fixed yet. 

I look forward to your feedback.

Best regards,
Jay

**Comment by gemguardian** [comment]
@Jay-lab-1

have you tested the branche: https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports?

You do mention 4.3 - We have not tested it on this version of Moodle.

**Comment by Jay-lab-1** [comment]
Thank you for the quick response. We have tested this with the version 4.1.0 of the plugin.

**Comment by gemguardian** [comment]
@Jay-lab-1 can you send me the JSON download of your query /settings so I can test it myself?

**Comment by Jay-lab-1** [comment]
@gemguardian 
Unfortunately, I currently only have the option of testing with the following version.
[Moodle] [4.3.5+ (Build: 20240705)]
 + PHP 8.2.4
 
 Upload of XML is not possible, therefore i renamed the file to *.txt
[Student count.txt](https://github.com/user-attachments/files/16164057/Student.count.txt)


Pie chart and line graph seem to work. but nothing is displayed in the bar chart

**Comment by gemguardian** [comment]
@Jay-lab-1 thank you - It might be a M4.3 / PHP 8.2 thing, but I will verify it on my end. It will be somewhere next week due to the holidays and planning

**Comment by gemguardian** [comment]
@Jay-lab-1 I have tested in M4.4 , PHP 8.1 and I have 2 out 3 - see screenshot below. 

@luukverhoeven the Line Graph still does not wat to appear for me, as I had in a previouw test. Could you please let me know how much time it would cost you to check this? We focus on PHP8.1 

![image](https://github.com/user-attachments/assets/27ef78c8-363c-48e9-a4e6-38899bd1b2b7)

When I take the URL from the inspect tool and put into Moodle I get this notification
![image](https://github.com/user-attachments/assets/3ad3cb24-1741-4a27-8002-8c6db5148a80)

**Comment by Jay-lab-1** [comment]
@gemguardian 
I tested it again and did not get an error via Moodle debugging, but via the Webdeveloper Console
![2024-08-06 08_10_12-Student count _ E-Learning](https://github.com/user-attachments/assets/57c7b109-b216-4e28-8982-77bbf4ac7f6c)

**Comment by gemguardian** [comment]
@Jay-lab-1 thank you for sharing the screenshot. 

@luukverhoeven see my previous post, could you please take another look why the line graph in PHP8.1 / 4.1 is not working? And let me know how much time it would cost you to check this? We focus on PHP8.1Maybe the information that Jay-lab shared is valuable for this as well.

**Comment by luukverhoeven** [comment]
@Jay-lab-1 Thank you for the information.
@gemguardian I will check and validate it. As soon as I have any details or an estimate, I will let you know.

**Comment by luukverhoeven** [comment]
@gemguardian I think it will take us 3 hours to investigate, find the issue, and resolve it.

**Comment by gemguardian** [comment]
@luukverhoeven thank you for the information.  I approve the hours. 

@Jay-lab-1  we will focus **only** on solving this in PHP8.1 and test 4.1

**Comment by gemguardian** [comment]
@luukverhoeven I just did a deep dive in this issue - and it's not been caused by the update  - as in it is not a regression. 
This is a known issue in configurable reports see: https://github.com/jleyva/moodle-block_configurablereports/issues/101 

That means I am marking this 'won't fix' - if anyone wants to sponsor solving this issue please contact sales@ltnc.nl
