### ISSUE TITLE
VCS Tag 4.1.0 missing

### ISSUE THREAD

**Issue by christianabila** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#3]
Hello,

the tag `4.1.0` is missing in this new repository. 

Is there any information available whether the old repository at https://github.com/jleyva/moodle-block_configurablereports will be discontinued?

Thanks,
Chris

**Comment by gemguardian** [comment]
@christianabila the 'old repository' will stay the active repository for releases to Moodle Plugin Database. We did this just for Moodle 4.1 financed by 3 organizations, to ensure our customers can continue using this plugin in 4.1 

We don't have plans to continue the maintaince of this block for other Moodle LMS versions then 4.1 - at least not without financial funding.
