### ISSUE TITLE
WSOD on php 8.0 or 8.1 using more than 1 condition

### ISSUE THREAD

**Issue by calbasi** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#4]
Hi, just updated my module to version 4.1, and I get a WSOD (white screen of dead) on my configurable report results page. I have not any log in my error.log and no errors are shown if I enable Moodle debug option.

It happens when I use 2 conditions (so I have to use a logical operator, like AND or OR).

When I use no conditions or just 1 condition, it's all right.

By the way, I'm using a "users report" type.

**Comment by gemguardian** [comment]
@calbasi thank you for reporting this issue. Could you please provided more ifnormation like your PHP and SQL version, and the JSON export. 

That said - please be aware that we don't have any funding left to continue fixing issues in this module. If you are interested in funding the necessary fix please let us know.

**Comment by gemguardian** [comment]
@calbasi Though I would ping you just to be sure if you could provided us the following information:
1. PHP version
2. SQL version/database use
3. an JSON/XML or TXT export of the report you are trying to get working

**Comment by calbasi** [comment]
> @calbasi Though I would ping you just to be sure if you could provided us the following information:

Sorry for the delay! :-)

> 
>     1. PHP version

Using Debian Stable and sury repos to have different php versions. For example:

PHP 8.2.22 (cli) (built: Aug  2 2024 16:01:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.22, Copyright (c), by Zend Technologies


> 
>     2. SQL version/database use

mysql  Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper


> 
>     3. an JSON/XML or TXT export of the report you are trying to get working

Not sure if I have the xml file you need, but I'm attaching it to you:

`
<?xml version="1.0" encoding="UTF-8" ?>
<report version="2024051300"><visible><![CDATA[1]]></visible>
<name><![CDATA[Estado de finalización por curso y unidad de negocio]]></name>
<summary><![CDATA[]]></summary>
<summaryformat><![CDATA[0]]></summaryformat>
<type><![CDATA[users]]></type>
<pagination><![CDATA[0]]></pagination>
<components><![CDATA[YTo0OntzOjc6ImNvbHVtbnMiO2E6MTp7czo4OiJlbGVtZW50cyI7YTo1OntpOjE7YTo1OntzOjI6ImlkIjtzOjE1OiJZMzhsWDMxRkJpdHVVeVciO3M6ODoiZm9ybWRhdGEiO086ODoic3RkQ2xhc3MiOjY6e3M6NjoiY29sdW1uIjtzOjk6ImZpcnN0bmFtZSI7czo5OiJjb2x1bW5hbWUiO3M6OToiRmlyc3RuYW1lIjtzOjU6ImFsaWduIjtzOjY6ImNlbnRlciI7czo0OiJzaXplIjtzOjA6IiI7czo0OiJ3cmFwIjtzOjA6IiI7czoxMjoic3VibWl0YnV0dG9uIjtzOjM6IkFkZCI7fXM6MTA6InBsdWdpbm5hbWUiO3M6OToidXNlcmZpZWxkIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czoxODoiVXNlcitwcm9maWxlK2ZpZWxkIjtzOjc6InN1bW1hcnkiO3M6OToiRmlyc3RuYW1lIjt9aToyO2E6NTp7czoyOiJpZCI7czoxNToiU0lMNDhIbjFQRzlUTEtvIjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjo2OntzOjY6ImNvbHVtbiI7czo4OiJsYXN0bmFtZSI7czo5OiJjb2x1bW5hbWUiO3M6ODoiTGFzdG5hbWUiO3M6NToiYWxpZ24iO3M6NjoiY2VudGVyIjtzOjQ6InNpemUiO3M6MDoiIjtzOjQ6IndyYXAiO3M6MDoiIjtzOjEyOiJzdWJtaXRidXR0b24iO3M6MzoiQWRkIjt9czoxMDoicGx1Z2lubmFtZSI7czo5OiJ1c2VyZmllbGQiO3M6MTQ6InBsdWdpbmZ1bGxuYW1lIjtzOjE4OiJVc2VyK3Byb2ZpbGUrZmllbGQiO3M6Nzoic3VtbWFyeSI7czo4OiJMYXN0bmFtZSI7fWk6MzthOjU6e3M6MjoiaWQiO3M6MTU6IkNuZ0gzNnlZRXVTY29wWSI7czo4OiJmb3JtZGF0YSI7Tzo4OiJzdGRDbGFzcyI6MDp7fXM6MTA6InBsdWdpbm5hbWUiO3M6MTQ6InVzZXJjb21wbGV0aW9uIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czoyOToiVXNlcitjb3Vyc2UrY29tcGxldGlvbitzdGF0dXMiO3M6Nzoic3VtbWFyeSI7czo0NToiVXNlcitjb21wbGV0aW9uK3N0YXR1cytmb3IrdGhlK2N1cnJlbnQrY291cnNlIjt9aTo1O2E6NTp7czoyOiJpZCI7czoxNToidzdlQnF5aDAzVG1OWVFLIjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjo2OntzOjY6ImNvbHVtbiI7czoxMDoicHJvZmlsZV9VTiI7czo5OiJjb2x1bW5hbWUiO3M6ODoiR2VyZW5jaWEiO3M6NToiYWxpZ24iO3M6NjoiY2VudGVyIjtzOjQ6InNpemUiO3M6MDoiIjtzOjQ6IndyYXAiO3M6MDoiIjtzOjEyOiJzdWJtaXRidXR0b24iO3M6NzoiQWdyZWdhciI7fXM6MTA6InBsdWdpbm5hbWUiO3M6OToidXNlcmZpZWxkIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czoyODoiQ2FtcG8rZGVsK3BlcmZpbCtkZWwrdXN1YXJpbyI7czo3OiJzdW1tYXJ5IjtzOjg6IkdlcmVuY2lhIjt9aTo2O2E6NTp7czoyOiJpZCI7czoxNToiSktYT3NhUnpOZmp0Z1BaIjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjo2OntzOjY6ImNvbHVtbiI7czo1OiJlbWFpbCI7czo5OiJjb2x1bW5hbWUiO3M6NToiRW1haWwiO3M6NToiYWxpZ24iO3M6NjoiY2VudGVyIjtzOjQ6InNpemUiO3M6MDoiIjtzOjQ6IndyYXAiO3M6MDoiIjtzOjEyOiJzdWJtaXRidXR0b24iO3M6NzoiQWdyZWdhciI7fXM6MTA6InBsdWdpbm5hbWUiO3M6OToidXNlcmZpZWxkIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czoyODoiQ2FtcG8rZGVsK3BlcmZpbCtkZWwrdXN1YXJpbyI7czo3OiJzdW1tYXJ5IjtzOjU6IkVtYWlsIjt9fX1zOjEwOiJjb25kaXRpb25zIjthOjI6e3M6ODoiZWxlbWVudHMiO2E6NDp7aTowO2E6NTp7czoyOiJpZCI7czoxNToiNzF3azRqWmhOTE44cTA0IjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjoyOntzOjU6InJvbGVzIjthOjE6e2k6MDtzOjE6IjUiO31zOjEyOiJzdWJtaXRidXR0b24iO3M6NzoiQWdyZWdhciI7fXM6MTA6InBsdWdpbm5hbWUiO3M6MjA6InVzZXJzaW5jdXJyZW50Y291cnNlIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czozOToiVXN1YXJpb3MrZW4rZWwraW5mb3JtZStkZWwrY3Vyc28rYWN0dWFsIjtzOjc6InN1bW1hcnkiO3M6Njk6IlVzdWFyaW8rY29uK2VsJTJGbG9zK3JvbCUyOGVzJTI5K3NlbGVjY2lvbmFkb3MrZW4rZWwraW5mb3JtZStkZStjdXJzbyI7fWk6MTthOjU6e3M6MjoiaWQiO3M6MTU6IjQzM1FZRzJVdHVxak5TeCI7czo4OiJmb3JtZGF0YSI7Tzo4OiJzdGRDbGFzcyI6NDp7czo1OiJmaWVsZCI7czo5OiJzdXNwZW5kZWQiO3M6ODoib3BlcmF0b3IiO3M6MzoiJTNEIjtzOjU6InZhbHVlIjtzOjE6IjAiO3M6MTI6InN1Ym1pdGJ1dHRvbiI7czo3OiJBZ3JlZ2FyIjt9czoxMDoicGx1Z2lubmFtZSI7czoxMDoiY3VzZXJmaWVsZCI7czoxNDoicGx1Z2luZnVsbG5hbWUiO3M6MzY6IkNvbmRpY2klQzMlQjNuK2RlbCtjYW1wbytkZWwrdXN1YXJpbyI7czo3OiJzdW1tYXJ5IjtzOjE2OiJTdXNwZW5kaWRvKyUzRCswIjt9aToyO2E6NTp7czoyOiJpZCI7czoxNToiM3NZaTJoYkNGQm5BdGJvIjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjo0OntzOjU6ImZpZWxkIjtzOjc6ImRlbGV0ZWQiO3M6ODoib3BlcmF0b3IiO3M6MzoiJTNEIjtzOjU6InZhbHVlIjtzOjE6IjAiO3M6MTI6InN1Ym1pdGJ1dHRvbiI7czo3OiJBZ3JlZ2FyIjt9czoxMDoicGx1Z2lubmFtZSI7czoxMDoiY3VzZXJmaWVsZCI7czoxNDoicGx1Z2luZnVsbG5hbWUiO3M6MzY6IkNvbmRpY2klQzMlQjNuK2RlbCtjYW1wbytkZWwrdXN1YXJpbyI7czo3OiJzdW1tYXJ5IjtzOjEzOiJCb3JyYWRvKyUzRCswIjt9aTozO2E6NTp7czoyOiJpZCI7czoxNToiVHhxVkx6NjY5V1BuZ0kyIjtzOjg6ImZvcm1kYXRhIjtPOjg6InN0ZENsYXNzIjo0OntzOjU6ImZpZWxkIjtzOjU6ImVtYWlsIjtzOjg6Im9wZXJhdG9yIjtzOjEyOiJMSUtFKyUyNSslMjUiO3M6NToidmFsdWUiO3M6MTY6ImFudGljaW1leC5jb20uZXMiO3M6MTI6InN1Ym1pdGJ1dHRvbiI7czoxMToiQSVDMyVCMWFkaXIiO31zOjEwOiJwbHVnaW5uYW1lIjtzOjEwOiJjdXNlcmZpZWxkIjtzOjE0OiJwbHVnaW5mdWxsbmFtZSI7czozNjoiQ29uZGljaSVDMyVCM24rZGVsK2NhbXBvK2RlbCt1c3VhcmlvIjtzOjc6InN1bW1hcnkiO3M6NTQ6IkRpcmVjY2klQzMlQjNuK2RlK2NvcnJlbytMSUtFKyUyNSslMjUrYW50aWNpbWV4LmNvbS5lcyI7fX1zOjY6ImNvbmZpZyI7Tzo4OiJzdGRDbGFzcyI6Mjp7czoxMzoiY29uZGl0aW9uZXhwciI7czoyMzoiYzIrYW5kK2MxK2FuZCtjMythbmQrYzQiO3M6MTI6InN1Ym1pdGJ1dHRvbiI7czoxMDoiQWN0dWFsaXphciI7fX1zOjExOiJwZXJtaXNzaW9ucyI7YToyOntzOjY6ImNvbmZpZyI7Tzo4OiJzdGRDbGFzcyI6MTp7czoxMzoiY29uZGl0aW9uZXhwciI7czowOiIiO31zOjg6ImVsZW1lbnRzIjthOjE6e2k6MDthOjU6e3M6MjoiaWQiO3M6MTU6IlhPTUtWdk5vcHp0eHAyVSI7czo4OiJmb3JtZGF0YSI7Tzo4OiJzdGRDbGFzcyI6MDp7fXM6MTA6InBsdWdpbm5hbWUiO3M6MTk6InJlcG9ydHNjYXBhYmlsaXRpZXMiO3M6MTQ6InBsdWdpbmZ1bGxuYW1lIjtzOjIzOiJDYXBhY2lkYWRlcytkZWwraW5mb3JtZSI7czo3OiJzdW1tYXJ5IjtzOjY0OiJVc3Vhcmlvcytjb24rbGErY2FwYWNpZGFkK21vb2RsZSUyRnNpdGUlM0F2aWV3cmVwb3J0cytoYWJpbGl0YWRhIjt9fX1zOjc6ImZpbHRlcnMiO2E6MTp7czo4OiJlbGVtZW50cyI7YToxOntpOjA7YTo1OntzOjI6ImlkIjtzOjE1OiJUZGNPc25LVHZSNFhCRHAiO3M6ODoiZm9ybWRhdGEiO086ODoic3RkQ2xhc3MiOjI6e3M6NToiZmllbGQiO3M6MTA6InByb2ZpbGVfVU4iO3M6MTI6InN1Ym1pdGJ1dHRvbiI7czo3OiJBZ3JlZ2FyIjt9czoxMDoicGx1Z2lubmFtZSI7czoxNjoiZnNlYXJjaHVzZXJmaWVsZCI7czoxNDoicGx1Z2luZnVsbG5hbWUiO3M6NDI6IkNhamErZGUrYiVDMyVCQXNxdWVkYStkZStjYW1wbytkZWwrdXN1YXJpbyI7czo3OiJzdW1tYXJ5IjtzOjEwOiJwcm9maWxlX1VOIjt9fX19]]></components>
<export><![CDATA[csv,json,ods,xls,]]></export>
<jsordering><![CDATA[1]]></jsordering>
<global><![CDATA[1]]></global>
<lastexecutiontime><![CDATA[0]]></lastexecutiontime>
<cron><![CDATA[0]]></cron>
<remote><![CDATA[0]]></remote>
</report>
`

**Comment by calbasi** [comment]
> That said - please be aware that we don't have any funding left to continue fixing issues in this module. If you are interested in funding the necessary fix please let us know.

It depends on :-) I can have some (not much) funds if we were lucky and it is an easy bug. I could help you to try to fix it if you provide me with guidance/support for debug, etc.

**Comment by gemguardian** [comment]
@calbasi I could reproduce the issue but I am not sure if it is caused by any changes on our side. 

If you provided a patch we surely would take a look at it.

**Comment by jupedega** [comment]
I have had the same problem. The problem is caused by this EvalWise class that extends EvalMath, when calling public function pfx($tokens, array $vars = []). Since the update to PHP 8, it is more strict with type inheritance. 

- **Type inheritance**: When one class inherits from another, the types of the parameters and the return values ​​of the methods must match exactly. If they do not match, a fatal error will be thrown.

The problem is that EvalMath expects public function pfx($tokens, $vars = []) instead of public function pfx($tokens, array $vars = []), precisely because of type inheritance. It is only necessary to change line 62 of the file from evalwise.class.php public function pfx($tokens, array $vars = []) to public function pfx($tokens, $vars = []). This would solve the error and allow you to chain the conditionals.

**Comment by calbasi** [comment]
You are right @jupedega ! I've made a pull request:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports/pull/7

Ps: how have you debbuged it? I had only a WSOD and nothing in my error.log... 

Gracias por todo!

**Comment by gemguardian** [comment]
Pull request accepted, thank you for the contribution.
